[package]
name = "enip"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
tokio = { version = "1", features = ["full"] }
cip = { workspace = true }
async-trait = "0.1.83"
tracing = {workspace = true}

[features]
default = ["tcp-client", "udp-client"]
tcp-client = []
udp-client = []